// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMweR5giv-UeqCBPv_zSrbcPtnhnl9_k',
    appId: '1:982256841444:web:804f497eb622079eeab2f1',
    messagingSenderId: '982256841444',
    projectId: 'winetopia-db6ec',
    authDomain: 'winetopia-db6ec.firebaseapp.com',
    storageBucket: 'winetopia-db6ec.firebasestorage.app',
    measurementId: 'G-JP5H61Q36P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK0Y0W2kynMVoVZKfpZyhufKlm-2FE31I',
    appId: '1:982256841444:android:335c5cd4710cfd4feab2f1',
    messagingSenderId: '982256841444',
    projectId: 'winetopia-db6ec',
    storageBucket: 'winetopia-db6ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2mnnb211eVwVIPXQ-osu4HkSnsEqTSd8',
    appId: '1:982256841444:ios:00a158da0a3f1444eab2f1',
    messagingSenderId: '982256841444',
    projectId: 'winetopia-db6ec',
    storageBucket: 'winetopia-db6ec.firebasestorage.app',
    iosBundleId: 'com.example.winetopiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2mnnb211eVwVIPXQ-osu4HkSnsEqTSd8',
    appId: '1:982256841444:ios:00a158da0a3f1444eab2f1',
    messagingSenderId: '982256841444',
    projectId: 'winetopia-db6ec',
    storageBucket: 'winetopia-db6ec.firebasestorage.app',
    iosBundleId: 'com.example.winetopiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMweR5giv-UeqCBPv_zSrbcPtnhnl9_k',
    appId: '1:982256841444:web:1cfdadbc569c474deab2f1',
    messagingSenderId: '982256841444',
    projectId: 'winetopia-db6ec',
    authDomain: 'winetopia-db6ec.firebaseapp.com',
    storageBucket: 'winetopia-db6ec.firebasestorage.app',
    measurementId: 'G-6RXJLYY6KS',
  );
}
